package com.pronted.utils

class SecurityResponseLabel {
    companion object {
        const val ME_CLASSWISE_TIME_TABLE_VIEW = "ME_CLASSWISE_TIME_TABLE_VIEW"
        const val ME_STUDENT_PROFILE_VIEW = "ME_STUDENT_PROFILE_VIEW"
        const val ME_STUDENT_PROFILE_EDIT = "ME_STUDENT_PROFILE_EDIT"
        const val ME_STUDENT_PROFILE_ADD = "ME_STUDENT_PROFILE_ADD"
        const val ME_STUDENT_ATTENDANCE_VIEW = "ME_STUDENT_ATTENDANCE_VIEW"
        const val ME_STUDENT_ATTENDANCE_EDIT = "ME_STUDENT_ATTENDANCE_EDIT"
        const val ME_STUDENT_ATTENDANCE_ADD = "ME_STUDENT_ATTENDANCE_ADD"
        const val ME_EXAM_SCHEDULE_VIEW = "ME_EXAM_SCHEDULE_VIEW"
        const val ME_EXAM_SCHEDULE_EDIT = "ME_EXAM_SCHEDULE_EDIT"
        const val ME_EXAM_SCHEDULE_ADD = "ME_EXAM_SCHEDULE_ADD"
        const val ME_EXAM_SCHEDULE_DELETE = "ME_EXAM_SCHEDULE_DELETE"
        const val ME_STUDENT_MARKS_VIEW = "ME_STUDENT_MARKS_VIEW"
        const val ME_STUDENT_MARKS_EDIT = "ME_STUDENT_MARKS_EDIT"
        const val ME_STUDENT_MARKS_ADD = "ME_STUDENT_MARKS_ADD"
        const val ME_MC_EMPLOYEE_NOTIFICATION = "ME_MC_EMPLOYEE_NOTIFICATION"
        const val ME_MC_ABSENT_REPORT = "ME_MC_ABSENT_REPORT"
        const val ME_MC_FEE_REMINDER = "ME_MC_FEE_REMINDER"
        const val ME_MC_GENERAL_NOTIFICATION = "ME_MC_GENERAL_NOTIFICATION"
        const val ME_MC_LATE_ENTRY = "ME_MC_LATE_ENTRY"
        const val ME_MC_MARKS_REPORT = "ME_MC_MARKS_REPORT"
        const val ME_MC_STUDENT_NOTIFICATION = "ME_MC_STUDENT_NOTIFICATION"
        const val ME_NOTICE_BOARD_VIEW = "ME_NOTICE_BOARD_VIEW"
        const val ME_NOTICE_BOARD_EDIT = "ME_NOTICE_BOARD_EDIT"
        const val ME_NOTICE_BOARD_ADD = "ME_NOTICE_BOARD_ADD"
        const val ME_NOTICE_BOARD_DELETE = "ME_NOTICE_BOARD_DELETE"
        const val ME_FEES_VIEW = "ME_FEES_VIEW"
        const val ME_FEES_EDIT = "ME_FEES_EDIT"
        const val ME_FEES_ADD = "ME_FEES_ADD"
        const val ME_PAYMENTS_VIEW = "ME_PAYMENTS_VIEW"
        const val ME_PAYMENTS_EDIT = "ME_PAYMENTS_EDIT"
        const val ME_PAYMENTS_ADD = "ME_PAYMENTS_ADD"
        const val ME_EMPLOYEE_PROFILE_VIEW = "ME_EMPLOYEE_PROFILE_VIEW"
        const val ME_EMPLOYEE_PROFILE_EDIT = "ME_EMPLOYEE_PROFILE_EDIT"
        const val ME_DASHBOARD_BIRTHDAYS_VIEW = "ME_DASHBOARD_BIRTHDAYS_VIEW"
        const val ME_DASHBOARD_FINANCE_VIEW = "ME_DASHBOARD_FINANCE_VIEW"
        //security group for displaying pay button
        const val ME_STUDENT_FEE_MAKE_PAYMENT = "ME_STUDENT_FEE_MAKE_PAYMENT"

    }
}